// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkHba4QXMmEeLwB2_MxJrqioBiESwtlyw',
    appId: '1:858641504005:web:835d7909dc4fc2c08a896c',
    messagingSenderId: '858641504005',
    projectId: 'home-management-f8b04',
    authDomain: 'home-management-f8b04.firebaseapp.com',
    storageBucket: 'home-management-f8b04.appspot.com',
    measurementId: 'G-XEEVD7CMPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACw_4eL7e5MU-2-vd4uZMXKTQ3ztDbb94',
    appId: '1:858641504005:android:72118d6dce8b0c318a896c',
    messagingSenderId: '858641504005',
    projectId: 'home-management-f8b04',
    storageBucket: 'home-management-f8b04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQmznSuJB-GUGWKrITycRb0EU_LHUREvY',
    appId: '1:858641504005:ios:e6f839c4ad243aec8a896c',
    messagingSenderId: '858641504005',
    projectId: 'home-management-f8b04',
    storageBucket: 'home-management-f8b04.appspot.com',
    iosBundleId: 'com.shuvo6904.homeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQmznSuJB-GUGWKrITycRb0EU_LHUREvY',
    appId: '1:858641504005:ios:e6f839c4ad243aec8a896c',
    messagingSenderId: '858641504005',
    projectId: 'home-management-f8b04',
    storageBucket: 'home-management-f8b04.appspot.com',
    iosBundleId: 'com.shuvo6904.homeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkHba4QXMmEeLwB2_MxJrqioBiESwtlyw',
    appId: '1:858641504005:web:97be5b2c2bbc75f18a896c',
    messagingSenderId: '858641504005',
    projectId: 'home-management-f8b04',
    authDomain: 'home-management-f8b04.firebaseapp.com',
    storageBucket: 'home-management-f8b04.appspot.com',
    measurementId: 'G-LP3GV1GQXV',
  );
}
